"""Centralized defaults for scripts."""

from __future__ import annotations

DEFAULT_MODEL_ID = "unsloth/llama-3.1-8b-unsloth-bnb-4bit"
DEFAULT_MAX_SEQ_LENGTH = 2048

DEFAULT_DATASET_DIR = "artifacts/dataset"
DEFAULT_LORA_DIR = "artifacts/lora"
DEFAULT_OLLAMA_OUT_DIR = "artifacts/ollama"
DEFAULT_OLLAMA_NAME = "finetuned-llama"
DEFAULT_GGUF_QUANT = "q4_k_m"

DEFAULT_VAL_RATIO = 0.02
DEFAULT_SEED = 3407

DEFAULT_LEARNING_RATE = 2e-4
DEFAULT_EPOCHS = 1.0
DEFAULT_PER_DEVICE_TRAIN_BATCH_SIZE = 1
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 8
DEFAULT_WARMUP_STEPS = 20
DEFAULT_LOGGING_STEPS = 10
DEFAULT_SAVE_STEPS = 200
DEFAULT_EVAL_STEPS = 200

DEFAULT_LORA_R = 16
DEFAULT_LORA_ALPHA = 16
DEFAULT_LORA_DROPOUT = 0.0

DEFAULT_SYSTEM_PROMPT = "You are a helpful assistant."
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.9
